apiVersion: v1
kind: ConfigMap
metadata:
  name: dagster-code-configmap
data:
  PROJECT_ID: $PROJECT_ID
  ENVIRONMENT: $ENVIRONMENT
  REGION: $REGION
  RAW_BUCKET_NAME: $RAW_BUCKET_NAME
  STAGING_BUCKET_NAME: $STAGING_BUCKET_NAME
  MISC_BUCKET_NAME: $MISC_BUCKET_NAME
  STAGING_DATASET_ID: $STAGING_DATASET_ID
  MART_DATASET_ID: $MART_DATASET_ID
  GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS