version: 2

sources:
- name: staging
  schema: "{{ env_var('DBT_DATASET_ID')}}"
  tables:
  - name: inc_albion_api_market_price
    meta:
      dagster:
        asset_key: ["inc_albion_api_market_price"] # This metadata specifies the corresponding Dagster asset for this dbt source.
        group: albion

  - name: full_albion_dump_market_price
    meta:
      dagster:
        asset_key: ["full_albion_dump_market_price"]
        group: albion

