from os import getenv


PROJECT_ID = getenv("PROJECT_ID")
REGION_ID = getenv("REGION_ID")
RAW_BUCKET_NAME = getenv("RAW_BUCKET_NAME")
STAGING_BUCKET_NAME = getenv("STAGING_BUCKET_NAME")
MISC_BUCKET_NAME = getenv("MISC_BUCKET_NAME")
DBT_DATASET_ID = getenv("DBT_DATASET_ID")
